---
collections:
  - name: ansible.utils
  - name: ansible.controller
  - name: community.aws
  - name: community.general
  - name: containers.podman
  - name: ansible.posix
  - name: cyberark.pas
  - name: community.windows
  - name: ansible.windows
  - name: amazon.aws
  - name: amazon.cloud
    type: git
    source: https://github.com/ansible-collections/amazon.cloud.git
