---
collections:
  - name: ansible.utils
  - name: ansible.controller
  - name: community.aws
  - name: community.general
  - name: containers.podman
  - name: ansible.posix
  - name: cyberark.pas
  - name: community.windows
  - name: ansible.windows
  - name: amazon.aws

